"""Look „editorial“: jede Folie ist ein Foto, abgedunkelt, darauf Text wie im
Magazin-Karussell (Carinas Vorlage vom 5. Oktober): große Serif-Titel (Fraunces
Light), breite fette Versalien (Syne ExtraBold), schlichter Fließtext (Poppins),
Pfeil-Listen, handgezogene Unterstreichungen, senkrechter Trennstrich, Monogramm
oben rechts.

Aufruf: python3 tools/editorial-look.py <eingabe.js> <ausgabe.js> <version>
Die Eingabe ist das Ergebnis von tools/frech-look.py.

Textauszeichnung pro Folie (jede Zeile eine Rolle, Leerzeile = Absatz):
  # Titel            große Serif (auf dem Deckblatt sehr groß)
  ## Titel           mittlere Serif
  > TEXT             breite fette Versalien
  - Punkt / → Punkt  Pfeil-Aufzählung
  ! Satz             fetter Einleitungssatz
  |                  senkrechter Trennstrich
  [mitte] / [links]  Ausrichtung der Folie
  normaler Text      Fließtext; **fett**, *fett + unterstrichen*, __unterstrichen__
Ohne Auszeichnung teilt der Zeichner selbst auf (Deckblatt: Titel + kurze
Schlusszeile in Versalien; Folgefolien: erster Satz Serif, Rest Fließtext).
"""
import json, sys

A, Z, VERSION = sys.argv[1], sys.argv[2], sys.argv[3]
s = open(A, encoding='utf-8').read()


def ersetze(alt, neu, anzahl=1):
    global s
    n = s.count(alt)
    if n != anzahl:
        sys.exit(f'{n}x statt {anzahl}x: {alt[:80]}')
    s = s.replace(alt, neu)


# Grundlage: der Frech-Look (Fotozuschnitt, Fotostil), alles andere hier drüber
i = s.index('"frech":{') + len('"frech":')
tiefe, j = 0, i
while True:
    if s[j] == '{': tiefe += 1
    elif s[j] == '}':
        tiefe -= 1
        if tiefe == 0: break
    j += 1
look = json.loads(s[i:j + 1])
SER, SANS, BREIT = 'Roxborough CF', 'Poppins', 'Syne Mag'  # Carinas eigene Lizenz (nur ihre App)
look.update({k: SER for k in ['fotoSchrift', 'deckblattFamilie', 'folgeFamilie', 'kastenSchrift', 'lisaSchrift',
                              'folgeSchrift', 'ablaufTitel', 'schriftart', 'unterSchrift']})
look.update({
    'magazin': 1, 'magSerif': SER, 'magSans': SANS, 'magBreit': BREIT, 'magMonogramm': 'cp', 'magHandArt': 'kursiv|versal|balken|kursiv|hand|versal|balken', 'magCoverWechsel': 1, 'magHand': 'Nothing You Could Do', 'magHandGewicht': '400', 'magCover': 'serif', 'magFeed': 'serif|kringel|flaeche|chat|pop|sticker|band|serif|durch|mitte|marker|zettel|zahl', 'magSticker': 'REAL TALK|15 JAHRE BÜHNE|SALES TALK|EHRLICH JETZT|KLAR TEXT', 'magDurchWorte': 'Ertappt.|Kenn ich.|Ups.|Same.|Echt jetzt?', 'magFlaeche': '#CEDF92', 'magFlaecheText': '#1E2B30', 'magFlaecheAkzent': '#3F6E78', 'magBand': 'rgba(18,16,15,0.86)', 'magCoverSerif': 'DMSerif Mag', 'magSerifGewicht': '400', 'magAkzent': '#CEDF92',
    'magDunkel': 0.2, 'magDunkelCover': 0.14, 'magAusrichtung': 'links',
    'versalFamilie': BREIT, 'versalAnteil': 0, 'fliessSchrift': SANS,
    # jede Folie bekommt ein Foto
    'textJede': 0, 'textAnteil': 0,
    # Fotos natürlich, leicht gedämpft, nicht so nah wie Kino
    'kino': 1, 'kinoSaettigung': 1.06, 'kinoHeben': 8, 'kinoKontrast': 1.04, 'kinoWarm': 0.04,
    'kinoSchwarz': 2, 'kinoWeiss': 252, 'kinoGamma': 0.88, 'kinoSplit': 1, 'kinoVignette': 0,
    'kinoBlauAnteil': 2, 'zuschnittZoom': 1.1,
})
AKZENTE = [('pfirsich', '#F6C8A8'), ('himmel', '#BFDDF0'), ('butter', '#F1E3B8')]
PREMIUM = {'magAkzent': '#F1F0A0', 'magFeed': 'serif|mitte|band|serif|kringel|flaeche|serif|durch|mitte|zettel|band', 'magCoverSerif': 'Roxborough CF', 'magCoverSerifGewicht': '400', 'magTitelSkala': 0.9, 'magTextSkala': 0.92, 'magTextLaufweite': 30, 'magHandSkala': 0.9, 'magCapsLaufweite': 240, 'magRahmen': 1, 'magFlaeche': '#EEECE5', 'magFlaecheText': '#1E2426', 'magFlaecheAkzent': '#3F6E78', 'kinoSaettigung': 0.9, 'kinoKontrast': 0.98, 'kinoHeben': 14, 'kinoVignette': 0.08, 'magDunkelCover': 0.18}
TYPO_BASIS = {'magMono': '#F7F1C4', 'magFeed': 'serif|mitte|band|serif|kringel|band|serif|mitte|serif|band|kringel',
              'magHandArt': 'kursiv|versal|balken|kursiv|versal|kursiv|balken', 'magCapsLaufweite': 260, 'magTextLaufweite': 20}
TYPO = [  # Titel immer Roxborough; Text, Versalien und kursive Zeile je Variante
    ('', {'magSans': 'HelveticaNeueBrand', 'magSansGewicht': '300', 'magBreit': 'HelveticaNeueBrand', 'magBreitGewicht': '500',
          'magKursiv': 'Cormorant Garamond', 'magKursivGewicht': '400', 'magKursivSkala': 1.18, 'fliessSchrift': 'HelveticaNeueBrand'}),
    ('-mode', {'magSans': 'Jost Mag', 'magSansGewicht': '300', 'magBreit': 'Jost Mag', 'magBreitGewicht': '500',
               'magKursiv': 'Instrument Serif', 'magKursivGewicht': '400', 'magKursivSkala': 1.12, 'fliessSchrift': 'Jost Mag'}),
    ('-modern', {'magSans': 'AspektaBrand', 'magSansGewicht': '400', 'magBreit': 'AspektaBrand', 'magBreitGewicht': '600',
                 'magKursiv': 'Bodoni Moda', 'magKursivGewicht': '400', 'magKursivSkala': 1.0, 'fliessSchrift': 'AspektaBrand'}),
]
FEED = {'magCoverSerif': 'Instrument Serif', 'magSerif': 'Instrument Serif', 'magSerifGewicht': '400', 'magCoverSerifGewicht': '400',
        'magKursiv': 'Instrument Serif', 'magKursivGewicht': '400', 'magKursivSkala': 1.25,
        'magSans': 'HelveticaNeueBrand', 'magSansGewicht': '300', 'magBreit': 'HelveticaNeueBrand', 'magBreitGewicht': '500',
        'fliessSchrift': 'HelveticaNeueBrand', 'magTitelSkala': 1.12, 'magTextSkala': 0.95, 'magTextLaufweite': 20, 'magCapsLaufweite': 300,
        'magHandArt': 'schreib|kursiv|schreibversal|schreib|kursiv', 'magKicker': 'REALTALK|SALES|STANDING', 'magKursivBetonung': 1, 'magLage': 'unten|oben|links|mitte|oben|unten|links', 'magTitelReihe': '1|1.12|0.86|1.05|0.92', 'magCoverKnapp': 1,
        'magFeed': 'serif|serif|band|serif|flaeche|serif|serif|band|serif|serif|flaeche', 'magAusrichtung': 'mitte', 'magCoverWechsel': 0,
        'magMonogramm': '', 'magNummer': 0, 'magRahmen': 0, 'magSignatur': 'schrift|caps',
        'magMono': '', 'magAkzent': '#FFFFFF', 'magFlaeche': '#63241E', 'magFlaecheText': '#F4EEE8', 'magFlaecheAkzent': '#F4EEE8',
        'magBand': 'rgba(15,15,15,0.97)', 'magDunkelCover': 0.16, 'magDunkel': 0.24,
        'kino': 1, 'kinoSaettigung': 0, 'kinoWarm': 0, 'kinoKontrast': 1.1, 'kinoHeben': 8, 'kinoGamma': 0.92, 'kinoVignette': 0.1, 'kinoSplit': 0}
RUHIG = {'magCoverSerif': 'HelveticaNeueBrand', 'magSerif': 'HelveticaNeueBrand', 'magSerifGewicht': '700', 'magCoverSerifGewicht': '700',
         'magTitelVersal': 1, 'magTitelGewicht': '700', 'magTitelFs': 0.062, 'magTitelLaufweite': -15, 'magTitelSkala': 1, 'magTitelReihe': '',
         'magKursivBetonung': 1, 'magKursivLaufGewicht': '300', 'magCoverInline': 1, 'magCoverKnapp': 0,
         'magSans': 'Inter', 'magSansGewicht': '300', 'magBreit': 'HelveticaNeueBrand', 'magBreitGewicht': '500', 'fliessSchrift': 'Inter',
         'magKursiv': 'HelveticaNeueBrand', 'magKursivGewicht': '300', 'magKursivSkala': 0.72, 'magHandArt': 'versal',
         'magTextSkala': 0.92, 'magTextLaufweite': 10, 'magCapsLaufweite': 260,
         'magLage': 'zentrum|rechts|untenmitte|oben|links|zentrum|untenmitte|rechts|oben', 'magFeed': 'scrap|serif|scrap|serif|scrap|band|scrap|serif|scrap|serif|scrap|serif|scrap|band', 'magAusrichtung': 'links', 'magCoverWechsel': 0,
         'magKicker': '', 'magSignatur': '', 'magMonogramm': '', 'magNummer': 0, 'magRahmen': 0, 'magMono': '#FFFFFF', 'magAkzent': '#FFFFFF',
         'magBand': 'rgba(15,15,15,0.96)', 'magDunkelCover': 0.04, 'magVerlaufCover': 0.38, 'magDunkel': 0.22,
         'kino': 1, 'kinoSaettigung': 0.95, 'kinoWarm': 0.02, 'kinoKontrast': 1.02, 'kinoHeben': 6, 'kinoGamma': 0.92, 'kinoVignette': 0, 'kinoSplit': 0}
OXBLOOD = {'magBand': 'rgba(92,28,34,0.96)',
           # edler: Roxborough (Carinas Lizenz) statt fetter Helvetica-Versalien, Weiterlauf Cormorant kursiv
           'magTitelVersal': 0, 'magCoverSerif': 'Roxborough CF', 'magCoverSerifGewicht': '400', 'magSerif': 'Roxborough CF', 'magSerifGewicht': '400',
           'magTitelSkala': 0.74, 'magKursiv': 'Cormorant Garamond', 'magKursivGewicht': '400', 'magKursivSkala': 1.0,
           'magKursivLaufSchrift': 'Cormorant Garamond', 'magKursivLaufGewicht': '400', 'magBreit': 'HelveticaNeueBrand', 'magBreitGewicht': '400',
           'scrapFarben': {
    'tf': 'Roxborough CF', 'tw': '400', 'tup': 0, 'tsk': 1.12, 'tlh': 1.0, 'tcs': -10, 'rf': 'Cormorant Garamond', 'rw': '400', 'rsk': 1.1,
    'lf': 'HelveticaNeueBrand', 'lw': '500', 'lcs': 300,
    'bg': ['#F0E8DD', '#C9B39D', '#5C1C22', '#F4EFE8'], 'rissPapier': '#5C1C22', 'rissText': '#F0E8DD',
    'tape1': 'rgba(201,179,157,0.85)', 'tape2': 'rgba(245,240,233,0.72)', 'tape3': 'rgba(201,179,157,0.9)',
    'papier': '#FBF8F3', 'bon': '#F6F1E9', 'hell': '#FBF8F3', 'akzent': '#D9C6B2', 'kornDunkel': 16,
    'gitter': 'rgba(90,75,65,0.15)', 'linie': '#DDD5CB', 'rand': '#B98A8A', 'polNotiz': '#0F0F0F',
    'st': {'riss': ['r1', 'r2', 'r3', 'r4', 'r5'], 'pol': ['o1', 'o2'], 'bon': ['w1', 'w2', 'w3', 'w4'], 'todo': ['s1', 's2', 's3', 's4']}}}
KLAR = {'magTitelVersal': 0, 'magCoverSerif': 'Instrument Serif', 'magCoverSerifGewicht': '400', 'magSerif': 'Instrument Serif', 'magSerifGewicht': '400',
        'magTitelSkala': 1, 'magCoverFs': 0.076, 'magH2Fs': 0.088, 'magSerifLaufweite': -45, 'magCoverInline': 0, 'magCoverKnapp': 0, 'magCoverEinTitel': 1,
        'magSkriptStandard': "schau mal|lies weiter|so geht's|ehrlich jetzt", 'magHandArt': 'skript', 'magHand': 'Nothing You Could Do', 'magHandGewicht': '400', 'magHandSkala': 1,
        'magLage': 'unten', 'magAusrichtung': 'mitte', 'magObenY': 0.1, 'magObenGesicht': 0.34,
        'magKlarFeed': 'dunkel|pabzug|sbon|sriss|dunkel|prahmen|cutschwarz|hell|dunkel|pkarte|sbon|spol|cutschwarz|stodo|pur|cutweiss', 'magSkriptJede': 2,
        'premiumHell': 0, 'premiumRahmenDunkel': 1, 'magKlarWeiss': '#FFFFFF', 'scrapFarben': {'bg': ['#5E1A21', '#5E1A21', '#0E0E0E', '#5E1A21'], 'rissPapier': '#0E0E0E', 'rissText': '#FFFFFF', 'notiz': '#F3EEE7', 'todoText': '#F3EEE7', 'tape1': 'rgba(227,106,44,0.82)', 'tape2': 'rgba(255,255,255,0.7)', 'tape3': 'rgba(227,106,44,0.9)', 'papier': '#FFFFFF', 'bon': '#FBFAF6', 'hell': '#FFFFFF', 'akzent': '#E36A2C', 'kornDunkel': 12, 'gitter': 'rgba(0,0,0,0.07)', 'linie': '#E4E1DD', 'rand': '#E36A2C', 'polNotiz': '#FFFFFF', 'tf': 'Instrument Serif', 'tw': '400', 'tup': 0, 'tsk': 1.18, 'tlh': 0.98, 'tcs': -35, 'rf': 'Instrument Serif', 'rw': '400', 'rsk': 1.05, 'lf': 'HelveticaNeueBrand', 'lw': '500', 'lcs': 300, 'st': {'riss': ['r1', 'r2', 'r3', 'r4', 'r5'], 'pol': ['e4', 'e6', 'e12', 'e13', 'e5'], 'bon': ['y1', 'y2', 'y3', 'y4'], 'todo': ['s1', 's2', 's3', 's4']},
                        'bonEl': ['e1', 'e3', 'e2', 'e15', 'e14', 'e11', 'e8', 'e10'], 'el': {'riss': ['e7', 'e3', 'e11', 'e15'], 'todo': ['e9', 'e8', 'e10', 'e14']}},
        'premiumElAbzug': 'e1|e11|e3|e15', 'premiumElKarte': 'e14|e8|e9|e10', 'premiumElRahmen': 'e7|e13|e4|e12', 'magKlarDunkel': 0.3, 'magKlarHell': 0.1, 'magKlarCut': 'k2|k3|k4|k7',
        'magPremiumCut': 'k3|k2|k7|k4',
        'magCoverBreite': 0.86, 'magTextMaxH': 0.34, 'magFeed': '', 'magMono': '#FFFFFF', 'magAkzent': '#FFFFFF',
        'magDunkelCover': 0, 'magVerlaufCover': 0.1, 'magDunkel': 0, 'magKursivBetonung': 0}
KLAR_PLAYFAIR = {'magCoverSerif': 'Playfair Display', 'magSerif': 'Playfair Display', 'magSerifLaufweite': -15, 'magCoverFs': 0.066, 'magH2Fs': 0.074,
                 'premiumSerif': 'Playfair Display', 'scrapFarben': {**KLAR['scrapFarben'], 'tf': 'Playfair Display', 'rf': 'Playfair Display', 'tcs': -10, 'tsk': 1.0}}
ZITRONE = [('zitrone-hell', '#F4EE6E'), ('zitrone-kraeftig', '#EDE64C'), ('zitrone-pastell', '#F1F0A0')]
weitere = ''.join(',"editorial-' + k + '":' + json.dumps({**look, **v}, ensure_ascii=False, separators=(',', ':')) for k, v in [('b', {'magFeed': ''}), ('pop', {'magFeed': '', 'magCover': 'pop'})]) + ''.join(',"editorial-' + k + '":' + json.dumps({**look, 'magAkzent': f}, ensure_ascii=False, separators=(',', ':')) for k, f in AKZENTE) + ''.join(',"editorial-' + k + '":' + json.dumps({**look, 'magAkzent': f, 'magFlaeche': f, 'magFlaecheText': '#1E2426'}, ensure_ascii=False, separators=(',', ':')) for k, f in ZITRONE) + ',"editorial-premium":' + json.dumps({**look, **PREMIUM}, ensure_ascii=False, separators=(',', ':')) + ''.join(',"editorial-premium-' + k + '":' + json.dumps({**look, **PREMIUM, 'magMono': f, 'magFeed': 'serif|mitte|band|serif|kringel|band|serif|durch|mitte|serif|band'}, ensure_ascii=False, separators=(',', ':')) for k, f in [('gelb', '#F7F1C4'), ('weiss', '#FFFFFF')]) + ''.join(',"editorial-typo' + k + '":' + json.dumps({**look, **PREMIUM, **TYPO_BASIS, **v}, ensure_ascii=False, separators=(',', ':')) for k, v in TYPO) + ',"editorial-feed":' + json.dumps({**look, **FEED}, ensure_ascii=False, separators=(',', ':')) + ',"editorial-ruhig":' + json.dumps({**look, **RUHIG}, ensure_ascii=False, separators=(',', ':')) + ',"editorial-ruhig-oxblood":' + json.dumps({**look, **RUHIG, **OXBLOOD}, ensure_ascii=False, separators=(',', ':')) + ',"editorial-klar":' + json.dumps({**look, **RUHIG, **KLAR}, ensure_ascii=False, separators=(',', ':')) + ',"editorial-klar-playfair":' + json.dumps({**look, **RUHIG, **KLAR, **KLAR_PLAYFAIR}, ensure_ascii=False, separators=(',', ':')) + ',"editorial-ruhig-pur":' + json.dumps({**look, **RUHIG, 'magFeed': 'serif|serif|band|serif|serif|serif|band'}, ensure_ascii=False, separators=(',', ':'))
ersetze('},"frech":', '},"editorial":' + json.dumps(look, ensure_ascii=False, separators=(',', ':')) + weitere + ',"frech":')

ZEICHNER = r'''if($e&&BS_KACHEL.magazin===1){const zFb=Pe.fabric,K=BS_KACHEL,zW=r,zH=n;
const SER=K.magSerif||"Fraunces Mag",HAND=K.magHand||"CaveatV3",HW=String(K.magHandGewicht||"700"),CSER=K.magCoverSerif||SER,SW=String(K.magSerifGewicht||"300"),SANS=K.magSans||"Poppins",WIDE=K.magBreit||"Syne Mag",WW=String(K.magBreitGewicht||"800"),KUR=K.magKursiv||"Fraunces Mag",KW=String(K.magKursivGewicht||"300"),KS=Number(K.magKursivSkala)||1,SB=String(K.magSansGewicht||"400");
try{await Promise.race([Promise.all([`${SW} 40px "${SER}"`,`400 40px "${CSER}"`,`${HW} 40px "${HAND}"`,`400 40px "${SANS}"`,`500 40px "${SANS}"`,`600 40px "${SANS}"`,`${WW} 40px "${WIDE}"`,`italic ${KW} 40px "${KUR}"`,`${SB} 40px "${SANS}"`,`400 40px "${K.magSchreib||"Courier Prime"}"`,`400 40px "${K.magSigSchrift||"Mrs Saint Delafield"}"`].map(zq=>document.fonts.load(zq).catch(()=>{}))),new Promise(zr=>setTimeout(zr,5e3))])}catch(zz){}
const zNo={selectable:!1,evented:!1};let AK=K.magAkzent||"#FFFFFF",TXT="#FFFFFF";
const zD=((i&&i.slideIndex)||0)===0?(K.magDunkelCover==null?.06:K.magDunkelCover):(K.magDunkel==null?.2:K.magDunkel);e.add(new zFb.Rect({left:0,top:0,width:zW,height:zH,fill:`rgba(0,0,0,${zD})`,...zNo}));
e.add(new zFb.Rect({left:0,top:0,width:zW,height:zH,...zNo,fill:new zFb.Gradient({type:"linear",coords:{x1:0,y1:0,x2:0,y2:zH},colorStops:[{offset:0,color:"rgba(0,0,0,0.08)"},{offset:.22,color:"rgba(0,0,0,0)"},{offset:.5,color:"rgba(0,0,0,0.04)"},{offset:1,color:`rgba(0,0,0,${((i&&i.slideIndex)||0)===0?(K.magVerlaufCover==null?.58:K.magVerlaufCover):.3})`}]})}));
const zCx=document.createElement("canvas").getContext("2d");
const zMs=(zs,zf,zfs,zcs)=>{zCx.font=zf;return zCx.measureText(zs).width+String(zs).length*(zcs||0)*zfs/1e3};
const zCover=((i&&i.slideIndex)||0)===0;
const ST={kick:{fam:K.magKickerSchrift||SANS,w:String(K.magKickerGewicht||"600"),fs:.021,lh:1.2,cs:520,up:1},amp:{fam:HAND,w:HW,fs:.1,lh:1.0,cs:0,max:1,min:.072},strike:{fam:CSER,w:"400",fs:.075,lh:1.1,cs:-10,max:3,min:.05},bl:{fam:SANS,w:SB,fs:.035,lh:1.35,cs:10,bub:1},br:{fam:SANS,w:"600",fs:.035,lh:1.35,cs:10,bub:1},zahl:{fam:WIDE,w:WW,fs:.3,lh:.92,cs:-30,max:1,min:.12},wm1:{fam:"Fraunces Mag",w:"300",fs:.095,lh:1.0,cs:-10,max:2,min:.06,it:1},wm2:{fam:CSER,w:"400",fs:.085,lh:1.02,cs:-10,max:3,min:.055},wm3:{fam:WIDE,w:WW,fs:.1,lh:1.0,cs:40,max:1,min:.05,up:1},hand:{fam:HAND,w:HW,fs:.086,lh:1.0,cs:0,max:3,min:.056},h1:{fam:SER,w:SW,fs:.13,lh:.95,cs:-20,max:5,min:.078},h2:{fam:SER,w:SW,fs:.072,lh:1.05,cs:-15,max:5},caps:{fam:WIDE,w:WW,fs:.033,lh:1.6,cs:140,up:1},lead:{fam:SANS,w:"600",fs:.031,lh:1.55,cs:20},body:{fam:SANS,w:SB,fs:.031,lh:1.65,cs:15},li:{fam:SANS,w:SB,fs:.032,lh:1.5,cs:15}};
const zFR=String(K.magFeed||"").split("|").filter(Boolean),zTyp0=zFR.length?zFR[((Number(t._tag)||0)%zFR.length+zFR.length)%zFR.length]:"",zTyp={kringel:"serif",durch:"serif",sticker:"serif",zettel:"serif",wortmix:"serif",marker:"pop",chat:"pop",zahl:"pop"}[zTyp0]||zTyp0;let zGim=zCover?zTyp0:"";const zStil=zTyp?(zTyp==="pop"?"pop":"serif"):K.magCover==="pop"||(K.magCover==="wechsel"&&(Number(t._tag)||0)%2===1)?"pop":"serif";if(zStil==="pop")ST.h1={fam:SANS,w:"600",fs:.088,lh:1.08,cs:-25,max:5,min:.068,pop:1};else if(K.magCoverSerif)ST.h1={...ST.h1,fam:CSER,w:String(K.magCoverSerifGewicht||"400"),fs:.115,lh:.98,cs:-10};if(zTyp==="band")ST.h1={...ST.h1,fam:SER,w:SW,fs:.105,lh:1.0,cs:-15,pop:0};if(!zCover){const zH2=zTyp||zStil;if(zH2==="pop")ST.h2={fam:SANS,w:"600",fs:.068,lh:1.08,cs:-20,max:5};else if(zH2!=="band"&&K.magCoverSerif)ST.h2={...ST.h2,fam:CSER,w:String(K.magCoverSerifGewicht||"400"),cs:-10}}if(zTyp==="band")e.add(new zFb.Rect({left:0,top:0,width:zW,height:zH,fill:K.magBand||"rgba(18,16,15,0.86)",...zNo}));if(zTyp==="mitte")e.add(new zFb.Rect({left:0,top:0,width:zW,height:zH,fill:"rgba(0,0,0,0.24)",...zNo}));if(zTyp==="flaeche"){e.add(new zFb.Rect({left:0,top:0,width:zW,height:zH,fill:K.magFlaeche||"#CEDF92",...zNo}));TXT=K.magFlaecheText||"#1E2B30";AK=K.magFlaecheAkzent||"#3F6E78"}
K.magMono&&zTyp!=="flaeche"&&(TXT=AK=String(K.magMono));ST.kom={...ST.hand,tilt:-7};{const zHAL=String(K.magHandArt||"").split("|").filter(Boolean),zHA=zHAL.length?zHAL[((Number(t._tag)||0)%zHAL.length+zHAL.length)%zHAL.length]:"hand";if(zHA==="kursiv"){ST.hand={fam:KUR,w:KW,fs:.076*KS,lh:1.1,cs:0,max:3,min:.055,it:1};ST.amp={...ST.hand,fs:.086*KS,max:1,min:.06}}else if(zHA==="schreib"){ST.hand={fam:K.magSchreib||"Courier Prime",w:"400",fs:.033,lh:1.5,cs:0,max:4,min:.025};ST.amp={...ST.hand,fs:.036,max:2}}else if(zHA==="schreibversal"){ST.hand={fam:K.magSchreib||"Courier Prime",w:"400",fs:.028,lh:1.6,cs:120,max:3,min:.022,up:1};ST.amp={...ST.hand,fs:.03,max:2}}else if(zHA==="versal"){ST.hand={fam:WIDE,w:WW,fs:.036,lh:1.6,cs:160,max:3,min:.026,up:1};ST.amp={...ST.hand,fs:.04,max:2}}else if(zHA==="skript"){ST.hand={fam:HAND,w:HW,fs:.05,lh:1.15,cs:0,max:3,min:.035};ST.amp={...ST.hand,fs:.06,max:2,min:.04}}else if(zHA==="balken"){ST.hand={fam:SANS,w:"500",fs:.043,lh:1.75,cs:10,max:3,min:.032,bar:1};ST.amp={...ST.hand,fs:.048,max:2}}else{ST.hand={...ST.hand,tilt:-3};ST.amp={...ST.amp,tilt:-3}}}{const zTS=Number(K.magTitelSkala)||1,zXS=Number(K.magTextSkala)||1,zHS=Number(K.magHandSkala)||1;const zTRl=String(K.magTitelReihe||"").split("|").filter(Boolean),zTR=zCover&&zTRl.length?Number(zTRl[((Number(t._tag)||0)%zTRl.length+zTRl.length)%zTRl.length])||1:1;ST.h1={...ST.h1,fs:ST.h1.fs*zTS*zTR,min:(ST.h1.min||.05)*zTS*zTR};ST.h2={...ST.h2,fs:ST.h2.fs*zTS};["body","li","lead","bl","br"].forEach(zk=>{ST[zk]={...ST[zk],fs:ST[zk].fs*zXS};K.magTextLaufweite!=null&&(ST[zk].cs=Number(K.magTextLaufweite))});["hand","amp"].forEach(zk=>ST[zk]={...ST[zk],fs:ST[zk].fs*zHS,min:ST[zk].min*zHS});K.magCapsLaufweite!=null&&(ST.caps={...ST.caps,cs:Number(K.magCapsLaufweite)})}
if(K.magTitelVersal!==1&&K.magSerifLaufweite!=null){ST.h1={...ST.h1,cs:Number(K.magSerifLaufweite)};ST.h2={...ST.h2,cs:Number(K.magSerifLaufweite)}}if(K.magCoverFs){ST.h1={...ST.h1,fs:Number(K.magCoverFs),min:Number(K.magCoverFs)*.62}}if(K.magH2Fs){ST.h2={...ST.h2,fs:Number(K.magH2Fs)}}if(K.magTitelVersal===1){ST.h1={...ST.h1,up:1,w:String(K.magTitelGewicht||"700"),fs:(Number(K.magTitelFs)||.07)*(Number(K.magTitelSkala)||1),lh:.96,cs:Number(K.magTitelLaufweite)||-10,min:.045,max:7}}
const zRuns=zs=>{const zo=[];let zb=!1,zu=!1,zc="";const zp=()=>{zc&&zo.push({t:zc,b:zb||zu,u:zu});zc=""};for(let k=0;k<zs.length;k++){const ch=zs[k];if(ch==="*"&&zs[k+1]==="*"){zp();zb=!zb;k++;continue}if(ch==="_"&&zs[k+1]==="_"){zp();zu=!zu;k++;continue}if(ch==="*"){zp();zu=!zu;continue}zc+=ch}zp();return zo};
const zSaetze=zx=>{const zr=[];let za="";String(zx||"").split(/\s+/).filter(Boolean).forEach(zw=>{za=za?za+" "+zw:zw;if(/[.!?:…]["»”“)’‘*]*$/.test(zw)){zr.push(za);za=""}});za&&zr.push(za);return zr};
let zAus=zTyp==="mitte"?"mitte":(K.magAusrichtung||"links");const zLLl=String(K.magLage||"").split("|").filter(Boolean),zLage=zCover&&zLLl.length?zLLl[((Number(t._tag)||0)%zLLl.length+zLLl.length)%zLLl.length]:"";let zLage2=zLage;zLage2==="rechts"&&t._zBox&&typeof t._zBox.x0==="number"&&(t._zBox.x0+t._zBox.x1)/2>.45&&(zLage2="links");zLage2==="rechts"&&(zAus="links");zLage2==="oben"&&zTyp!=="band"&&zTyp!=="flaeche"&&t._zBox&&typeof t._zBox.y0==="number"&&t._zBox.y0<(K.magObenGesicht||.55)&&(zLage2="unten");zLage2==="links"&&(zAus="links");zLage2==="zentrum"&&t._zBox&&typeof t._zBox.y0==="number"&&t._zBox.y0<.62&&t._zBox.y1>.3&&(zLage2="untenmitte");(zLage2==="zentrum"||zLage2==="untenmitte")&&(zAus="mitte");zCover&&K.magCoverWechsel===1&&zTyp0!=="chat"&&(Number(t._tag)||0)%2===1&&(zAus="mitte");const zBl=[];
let zKickT="",zRoh=String(t.text||"").replace(/\r/g,"");{const zm=/^\s*\[([^\]\n]{2,24})\]\s*/.exec(zRoh);if(zm&&!/^(mitte|links)$/i.test(zm[1])){zKickT=zm[1].trim();zRoh=zRoh.slice(zm[0].length)}}const zZl=zRoh.split("\n");
const zMark=zZl.some(zq=>/^\s*(#{1,2}\s|>\s|[-•→]\s|->\s|!\s|~\s|\|\s*$|\[(mitte|links)\]\s*$)/i.test(zq));
if(zMark){zZl.forEach(zq=>{const z=zq.trim();if(!z){zBl.push({k:"gap"});return}let m;
if(/^\[mitte\]$/i.test(z)){zAus="mitte";return}if(/^\[links\]$/i.test(z)){zAus="links";return}
if(m=/^##\s+(.*)$/.exec(z))return zBl.push({k:"h2",s:m[1]});if(m=/^#\s+(.*)$/.exec(z))return zBl.push({k:zCover?"h1":"h2",s:m[1]});
if(m=/^>\s+(.*)$/.exec(z))return zBl.push({k:"caps",s:m[1]});if(m=/^(?:[-•→]|->)\s+(.*)$/.exec(z))return zBl.push({k:"li",s:m[1]});
if(m=/^~\s+(.*)$/.exec(z))return zBl.push({k:"hand",s:m[1]});if(m=/^!\s+(.*)$/.exec(z))return zBl.push({k:"lead",s:m[1]});if(/^\|$/.test(z))return zBl.push({k:"div"});zBl.push({k:"body",s:z})})}
else{const zP=zRoh.split(/\n/).map(zq=>zq.trim()).filter(Boolean);
if(zCover){let zAll=zP.join(" "),zAmp="";const zAi=zAll.search(/(^|\s)&\s/);if(zAi>=0){zAmp=zAll.slice(zAi).trim();zAll=zAll.slice(0,zAi).trim()}const zS=zSaetze(zAll);let zh=zS[0]||"",zr=zS.slice(1),zHand="";if(zh.replace(/\*/g,"").length>50){let zc=-1;const zIn=zx=>{const zv=zh.slice(0,zx);return(zv.match(/[\u201e\u00bb]/g)||[]).length>(zv.match(/[\u201c\u201d\u00ab]/g)||[]).length||((zv.match(/"/g)||[]).length%2===1)};const zk=zh.indexOf(", ",15);if(zk>0&&zk<=60&&!zIn(zk))zc=zk;else{const zm=/\s(und|oder|weil|aber|statt|bis|wenn|obwohl|damit|während|nachdem|sobald)\s/g;let zq;while((zq=zm.exec(zh))){if(zq.index>=18&&zq.index<=60&&!zIn(zq.index)){zc=zq.index;break}}}if(zc>0){zHand=zh.slice(zc).replace(/^[,\s]+/,"");zh=zh.slice(0,zc)}}if(!zHand&&zr.length&&zr[0].replace(/\*/g,"").length<=(zAmp?20:70))zHand=zr.shift();if(zAmp&&zHand&&zHand.replace(/\*/g,"").length>20){zr.unshift(zHand);zHand=""}zBl.push({k:"h1",s:zh});zHand&&zBl.push({k:"hand",s:zHand});zr.length&&zBl.push({k:"body",s:zr.join(" ")});zAmp&&zBl.push({k:"amp",s:zAmp})}
else{const zV=((Number(t._tag)||0)+((i&&i.slideIndex)||0))%3,zLen=zx=>String(zx).replace(/\*/g,"").length;
const zUL=zx=>{zx=String(zx);if(/\*/.test(zx)||zx.length<30)return zx;const zm=/[.!?:…]+$/.exec(zx),ze=zm?zm.index:zx.length;let zs=zx.lastIndexOf(", ",ze)+2;if(zs<2||ze-zs<8||ze-zs>55){const zw=zx.slice(0,ze).split(" ");if(zw.length<6)return zx;zs=ze-zw.slice(-3).join(" ").length}return zx.slice(0,zs)+"*"+zx.slice(zs,ze)+"*"+zx.slice(ze)};
let zIntro="",zItems=[],zRest=[];const zNum=zP.map(zq=>/^\d+[.)]\s+/.test(zq));
if(zP.length>=3){let zk=/:$/.test(zP[0])?1:0;zk&&(zIntro=zP[0]);let zj=zk;while(zj<zP.length&&zLen(zP[zj])<=70&&(zNum[zj]||!/[.!?]$/.test(zP[zj])))zj++;if(zj-zk<3){zj=zk;while(zj<zP.length&&zLen(zP[zj])<=70)zj++;if(zj-zk>=4&&zj===zP.length)zj--}if(zj-zk>=3){zItems=zP.slice(zk,zj).map(zq=>zq.replace(/^\d+[.)]\s+/,""));zRest=zP.slice(zj)}else zIntro=""}
let zZit=0,zPaar=0;if(!zItems.length){const zS0=zSaetze(zP.join(" ")),zQ=zS0.map(zx=>/^[„"»«‚]/.test(zx)&&/[“”"«»‘’][.!?]?$/.test(zx));const zPr=[];for(let zi=0;zi<zS0.length-1;zi++)/:$/.test(zS0[zi])&&zLen(zS0[zi])<=28&&zQ[zi+1]&&zPr.push(zi);if(zPr.length>=2){zPaar=1;const z0=zPr[0];z0>0&&zBl.push({k:"body",s:zS0.slice(0,z0).join(" ")});zPr.forEach(zi=>{zBl.push({k:"caps",s:zS0[zi].replace(/:$/,""),paar:1});zBl.push({k:"h2",s:zS0[zi+1],paar:1})});const zr=zS0.filter((zx,zi)=>zi>z0&&!zPr.includes(zi)&&!zPr.includes(zi-1));zr.length&&zBl.push({k:"body",s:zUL(zr.join(" "))})}else if(zQ.filter(Boolean).length>=2){const zf=zQ.indexOf(!0);zIntro=zS0.slice(0,zf).join(" ");zItems=zS0.filter((zx,zi)=>zQ[zi]);zRest=zS0.filter((zx,zi)=>zi>zf&&!zQ[zi]);zZit=1}}
if(!zItems.length&&!zPaar){const zA=zP.join(" "),zm=/^(.{8,110}?:)\s+(.+?)([.!?])?$/.exec(zA);if(zm){const zq=zm[2].split(/,\s*|\s+und\s+|\s+oder\s+|\s+sowie\s+/).map(zx=>zx.trim()).filter(Boolean);if(!/[.!?]\s/.test(zm[1])&&zq.length>=3&&zq.every(zx=>zx.length<=42&&!/[.!?]\s/.test(zx))){zIntro=zm[1];zItems=zq}}}
if(zPaar){}else if(zItems.length){zIntro&&zBl.push({k:zZit&&zLen(zIntro)<=110?"h2":"body",s:zIntro});const zCaps=!zZit&&zItems.length<=7&&zItems.every(zx=>zLen(zx)<=20);zItems.forEach(zx=>zBl.push({k:zCaps?"caps":"li",s:zx.replace(/[.;]$/,"")}));const zR=zSaetze(zRest.join(" "));if(zR.length){const zl=zR[zR.length-1];if(!zCaps&&zLen(zl)<=48){zR.length>1&&zBl.push({k:"body",s:zR.slice(0,-1).join(" ")});zBl.push({k:"caps",s:zl.replace(/\.$/,"")})}else zBl.push({k:"body",s:zUL(zR.join(" "))})}}
else{const zS=zSaetze(zP.join(" ")),zN=zS.length,zH2=zx=>zLen(zx)<=110?"h2":"body";
const zFin=zr=>{if(!zr.length)return;let zc="";zr.length>=2&&zLen(zr[zr.length-1])<=45&&(zc=zr.pop());const zk=zr.findIndex(zx=>/:$/.test(zx));if(zk>=0&&zk<zr.length-1){zk>0&&zBl.push({k:"body",s:zr.slice(0,zk).join(" ")});zBl.push({k:"lead",s:zr[zk]});zBl.push({k:"body",s:zUL(zr.slice(zk+1).join(" "))})}else zBl.push({k:"body",s:zUL(zr.join(" "))});zc&&zBl.push({k:"caps",s:zc.replace(/\.$/,"")})};
if(zN<=1){const zx=zS[0]||"";zLen(zx)<=100?(zV===0&&(zAus="mitte"),zBl.push({k:"h2",s:zx})):zBl.push({k:"body",s:zUL(zx)})}
else if(zN===2){if(zV===0){zAus="mitte";zBl.push({k:zH2(zS[0]),s:zS[0]},{k:"div"},{k:"body",s:zUL(zS[1])})}else if(zV===1)zBl.push({k:"body",s:zS[0]},{k:zH2(zS[1]),s:zS[1]});else zBl.push({k:zH2(zS[0]),s:zS[0]},{k:"body",s:zUL(zS[1])})}
else if(zV===0){zAus="mitte";zBl.push({k:zH2(zS[0]),s:zS[0]},{k:"body",s:zS[1]},{k:"div"});zFin(zS.slice(2))}
else if(zV===1){zBl.push({k:"body",s:zS[0]},{k:zH2(zS[1]),s:zS[1]});zFin(zS.slice(2))}
else{zBl.push({k:zH2(zS[0]),s:zS[0]});zFin(zS.slice(1))}}}}
while(zBl.length&&zBl[zBl.length-1].k==="gap")zBl.pop();while(zBl.length&&zBl[0].k==="gap")zBl.shift();let zGimZettel="";
const zWahl=(zl,zd)=>{const zq=String(zl||"").split("|").filter(Boolean);return zq.length?zq[((Number(t._tag)||0)%zq.length+zq.length)%zq.length]:zd};
if(zGim&&!zMark){const zI1=zBl.findIndex(zq=>zq.k==="h1"),zIH=zBl.findIndex(zq=>zq.k==="hand");
if(zGim==="zahl"){const zS=zSaetze(zRoh.replace(/\n/g," ")),zIx=zS.findIndex(zq=>/\d/.test(zq));if(zIx<0)zGim="kringel";else{const zm=/\d[\d.,]*(?:\s?(?:%|€|Euro|k))?/.exec(zS[zIx]),zv=zS[zIx].slice(0,zm.index).trim(),zn=zS[zIx].slice(zm.index+zm[0].length).replace(/[.!?:]+$/,"").trim(),zh=zS.slice(zIx+1).find(zq=>zq.length<=70)||"";zBl.length=0;zv&&zBl.push({k:"lead",s:zv});zBl.push({k:"zahl",s:zm[0]});zn&&zBl.push({k:"caps",s:zn.length>34?zn.slice(0,zn.lastIndexOf(" ",34))+" …":zn});zh&&zBl.push({k:"hand",s:zh})}}
if((zGim==="durch"||zGim==="zettel")&&zIH<0||zGim==="durch"&&/^&/.test(zBl[zIH].s))zGim="kringel";
if(zGim==="durch"){zBl[zIH].k="strike";zBl.splice(zIH,0,{k:"hand",s:zWahl(K.magDurchWorte,"Ertappt."),kom:1})}
if(zGim==="zettel"){zGimZettel=zBl[zIH].s;zBl.splice(zIH,1)}
if(zGim==="chat"&&zI1>=0){zBl[zI1].k="bl";zIH>=0&&(zBl[zIH].k="br")}
if(zGim==="wortmix"&&zI1>=0){const zw=String(zBl[zI1].s).replace(/\*+/g,"").trim().split(/\s+/);const zn=[];zw.length>1&&zn.push({k:"wm1",s:zw[0]});zw.length>2&&zn.push({k:"wm2",s:zw.slice(1,-1).join(" ")});zn.push({k:"wm3",s:zw[zw.length-1]});zBl.splice(zI1,1,...zn)}}
if(zCover&&!zMark&&K.magKicker){const zKw=zKickT||zWahl(K.magKicker,"");zKw&&zBl.unshift({k:"kick",s:zKw})}
if(zCover&&!zMark&&K.magCoverEinTitel===1){const zRw=zRoh.split(/\n/).map(q=>q.trim()).filter(Boolean).join(" "),zAi=zRw.search(/(^|\s)&\s/),zTit=(zAi>=0?zRw.slice(0,zAi):zRw).replace(/\*+|__/g,"").trim(),zAm=(zAi>=0?zRw.slice(zAi).replace(/\*+|__/g,"").trim():(K.magSkriptJede&&(Number(t._tag)||0)%Number(K.magSkriptJede)!==0?"":zWahl(K.magSkriptStandard,""))).replace(/^&\s*/,"");zBl.length=0;zTit&&zBl.push({k:"h1",s:zTit});zAm&&zBl.push({k:"amp",s:zAm})}
if(zCover&&!zMark&&K.magCoverInline===1){const zT1=zBl.find(q=>q.k==="h1"),zHd=zBl.find(q=>q.k==="hand"&&!q.kom);if(zT1&&zHd){zT1.s=String(zT1.s).replace(/\*/g,"").trim()+" *"+String(zHd.s).replace(/\*/g,"").trim()+"*";zBl.splice(zBl.indexOf(zHd),1)}}
if(zCover&&!zMark&&K.magCoverKnapp===1){const zA=zBl.find(q=>q.k==="amp"),zHd=zBl.find(q=>q.k==="hand"&&!q.kom),zEin=zA||zHd,zKeep=new Set(zBl.filter(q=>q.k==="kick"||q.k==="h1"||q.k==="strike"||q.kom||q===zEin||q===zHd&&String(q.s).replace(/\*/g,"").length<=20));for(let zi=zBl.length-1;zi>=0;zi--)!zKeep.has(zBl[zi])&&zBl.splice(zi,1)}

const L=zW*(zCover&&zLage2==="rechts"?.43:.11),MAXW=zW*(zCover?(zLage2==="rechts"?.49:(K.magCoverBreite||.78)):.76),LI=zW*.105;
const zWrap=(zruns,st,fs,mw)=>{const zws=[];zruns.forEach(ru=>String(ru.t).split(/(\s+)/).forEach(zw=>{zw&&zws.push({t:zw,b:ru.b,u:ru.u,c:ru.c,i:ru.i,sp:/^\s+$/.test(zw)})}));
const zf=(zb,zi)=>`${st.it||zi?"italic ":""}${zb&&st.fam===SANS?"600":zi&&K.magKursivLaufGewicht?String(K.magKursivLaufGewicht):st.w} ${fs}px "${zi&&K.magKursivLaufSchrift?K.magKursivLaufSchrift:st.fam}"`;const zl=[];let zc=[],zcw=0;
const zend=()=>{while(zc.length&&zc[zc.length-1].sp)zcw-=zc.pop().w;zc.length&&zl.push({segs:zc,w:zcw});zc=[];zcw=0};
zws.forEach(zd=>{const zw=zMs(zd.t,zf(zd.b,zd.i),fs,st.cs);if(zd.sp){zc.length&&(zc.push({...zd,w:zw}),zcw+=zw);return}if(zcw+zw>mw&&zc.length)zend();zc.push({...zd,w:zw});zcw+=zw});zend();return zl};
zBl.forEach((zb,zx)=>{zb.k==="caps"&&((zBl[zx-1]||{}).k==="caps"||(zBl[zx+1]||{}).k==="caps")&&(zb.reihe=1)});let zK=1;const zBau0=()=>zBl.map(zb=>{if(zb.k==="gap"||zb.k==="div")return{...zb,h:zb.k==="div"?zH*.095:zH*.012,lines:[]};const st=ST[zb.kom?"kom":zb.k];let fs=zW*st.fs*zK;
let txt=String(zb.s||"");const zIB=K.magKursivBetonung===1&&st.fam!==SANS&&!st.it&&(!st.up||zb.k==="h1")&&/\*[^*]+\*/.test(txt);if(!zIB&&(st.fam!==SANS||zb.k==="h1"))txt=txt.replace(/\*+|__/g,"");if(st.up)txt=txt.toLocaleUpperCase("de-DE");
const zr=zIB?txt.replace(/\*\*/g,"").split(/(\*[^*]+\*)/).filter(Boolean).map(zq=>/^\*.*\*$/.test(zq)?{t:zq.slice(1,-1),b:!1,u:!1,i:1}:{t:zq,b:!1,u:!1}):st.fam===SANS?zRuns(txt):[{t:txt,b:!1,u:!1}];if(zGim==="marker"&&zb.k==="h1"&&zr.length){const zt=zr.map(zq=>zq.t).join("").trim(),zw=zt.split(/\s+/);let zn=1;while(zn<zw.length-1&&zw.slice(-zn).join(" ").length<12)zn++;const zA0=zw.slice(0,-zn).join(" "),zA1=zw.slice(-zn).join(" ");zr.length=0;zA0&&zr.push({t:zA0+" ",b:!1,u:!1});zr.push({t:zA1,b:!1,u:!1,c:1})}else if(st.pop&&zr.length&&!zBl.some(zq=>zq.k==="hand")){const zl0=zr[zr.length-1],zi=zl0.t.trimEnd().lastIndexOf(" ");zi>0?zr.splice(zr.length-1,1,{...zl0,t:zl0.t.slice(0,zi+1)},{...zl0,t:zl0.t.slice(zi+1),c:1}):(zl0.c=1)}const mw=zb.k==="li"?MAXW-LI:st.bub?zW*.6:zb.k==="strike"?MAXW*.92:MAXW;let lines=zWrap(zr,st,fs,mw);
if(st.max)for(let k=0;k<40&&(lines.length>st.max||lines.some(zl=>zl.w>mw))&&!(st.min&&fs<=zW*st.min*zK&&!lines.some(zl=>zl.w>mw));k++){fs*=.94;lines=zWrap(zr,st,fs,mw)}if(zb.reihe)for(let k=0;k<20&&lines.length>1&&fs>zW*.03;k++){fs*=.95;lines=zWrap(zr,st,fs,mw)}
if(lines.length>1&&!st.bub&&zb.k!=="li"){const zn=lines.length;let lo=mw*.5,hi=mw;for(let k=0;k<10;k++){const zm=(lo+hi)/2;zWrap(zr,st,fs,zm).length>zn?lo=zm:hi=zm}lines=zWrap(zr,st,fs,hi)}return{...zb,st,fs,lines,h:lines.length*fs*st.lh+(st.bub?fs*1.2:0)}});const zBau=()=>{const zb0=zBau0();const zm=Math.min(...zb0.filter(zq=>zq.reihe).map(zq=>zq.fs),1e9);return zm<1e9?zb0.map(zq=>{if(!zq.reihe||zq.fs===zm)return zq;const lines=zWrap([{t:String(zq.s).replace(/\*+|__/g,"").toLocaleUpperCase("de-DE"),b:!1,u:!1}],zq.st,zm,MAXW);return{...zq,fs:zm,lines,h:lines.length*zm*zq.st.lh}}):zb0};
const zGap=(za,zb)=>za.k==="kick"?zH*.024:za.paar&&zb.paar&&za.k==="caps"?zH*.012:za.paar&&zb.paar?zH*.04:zb.k==="amp"?zH*.036:za.st&&za.st.bub&&zb.st&&zb.st.bub?zH*.014:/^wm/.test(za.k)&&/^wm/.test(zb.k)?zH*.004:za.k==="hand"&&za.kom?zH*.004:za.k==="zahl"?zH*.012:za.k==="lead"&&zb.k==="zahl"?zH*.004:za.k==="h1"&&zb.k==="hand"?zH*.014:za.k==="hand"?zH*.026:za.k==="caps"&&zb.k==="caps"?zH*.008:za.k==="li"&&zb.k==="li"?zH*.026:zb.k==="div"||za.k==="div"?zH*.03:za.k==="h1"?zH*.03:za.k==="h2"?zH*.038:za.k==="caps"?zH*.03:za.k==="lead"?zH*.02:zH*.028;
let zB=zBau(),zT=0;const zSum=()=>{zT=zB.reduce((za,zb,zx)=>za+zb.h+(zx<zB.length-1?zGap(zb,zB[zx+1]):0),0)};zSum();
for(let k=0;k<30&&zT>zH*(zGim==="zettel"||zGim==="sticker"?.52:zCover&&K.magTextMaxH?K.magTextMaxH:.7)&&zK>.6;k++){zK*=.94;zB=zBau();zSum()}
let y=zCover&&zLage2?(zLage2==="oben"?zH*(K.magObenY||.15):(zLage2==="mitte"||zLage2==="zentrum")?Math.max(zH*.14,zH*.5-zT/2):Math.max(zH*.14,zH*.86-zT)):zCover?(zTyp==="mitte"||zTyp==="flaeche"||zTyp==="band"?Math.max(zH*.14,zH*.53-zT/2):Math.max(zH*.14,zH*(zTyp==="band"?.9:.86)-zT)):Math.max(zH*.14,zH*.56-zT/2);zLage2==="oben"&&zTyp!=="band"&&zTyp!=="flaeche"&&e.add(new zFb.Rect({left:0,top:0,width:zW,height:zH*.62,selectable:!1,evented:!1,fill:new zFb.Gradient({type:"linear",coords:{x1:0,y1:0,x2:0,y2:zH*.62},colorStops:[{offset:0,color:K.magObenHell?"rgba(255,255,255,0.42)":`rgba(0,0,0,${zkObenA==null?.5:zkObenA})`},{offset:.55,color:K.magObenHell?"rgba(255,255,255,0.18)":`rgba(0,0,0,${zkObenA==null?.28:zkObenA*.5})`},{offset:1,color:"rgba(0,0,0,0)"}]})}));zCover&&zLage2==="zentrum"&&zTyp!=="band"&&zTyp!=="flaeche"&&e.add(new zFb.Rect({left:0,top:0,width:zW,height:zH,fill:"rgba(0,0,0,0.26)",...zNo}));zCover&&zTyp==="mitte"&&e.add(new zFb.Line([zW/2-zW*.05,y-zH*.045,zW/2+zW*.05,y-zH*.045],{stroke:AK,strokeWidth:Math.max(2,zW*.004),...zNo}));
let zLW=null,zHY=null,zAmpL=null;const zDurch=[],zY0=y;let zSch=new zFb.Shadow({color:zCover?"rgba(0,0,0,0.42)":"rgba(0,0,0,0.28)",blur:zW*(zCover?.018:.012),offsetX:0,offsetY:0});zTyp==="flaeche"&&(zSch=void 0);zkKeinSchatten&&(zSch=void 0);if(zCover&&K.magCoverTextFarbe&&zLage2==="oben"){TXT=AK=String(K.magCoverTextFarbe);zSch=void 0}zCover&&K.magObenHell&&zLage==="oben"&&zLage2==="unten"&&e.add(new zFb.Rect({left:0,top:zH*.42,width:zW,height:zH*.58,...zNo,fill:new zFb.Gradient({type:"linear",coords:{x1:0,y1:0,x2:0,y2:zH*.58},colorStops:[{offset:0,color:"rgba(0,0,0,0)"},{offset:1,color:"rgba(0,0,0,0.6)"}]})}));
const zStrich=(x1,x2,yy,fs)=>{let zh=0;const zs=String(t.text||"")+x1;for(let k=0;k<zs.length;k++)zh=(zh*31+zs.charCodeAt(k))%9973;const zj=k=>((zh*(k+3))%7-3)/3*fs*.035;const sw=Math.max(1.2,zW*.0024);
e.add(new zFb.Path(`M ${x1} ${yy+zj(1)} Q ${(x1+x2)/2} ${yy+zj(2)+fs*.03} ${x2} ${yy+zj(3)}`,{fill:"",stroke:AK,strokeWidth:sw,strokeLineCap:"round",...zNo}));
e.add(new zFb.Path(`M ${x1+fs*.15} ${yy+fs*.09+zj(4)} Q ${(x1+x2)/2} ${yy+fs*.06+zj(5)} ${x2-fs*.1} ${yy+fs*.1+zj(6)}`,{fill:"",stroke:AK,strokeWidth:sw*.6,strokeLineCap:"round",opacity:.85,...zNo}))};
zB.forEach((zb,zx)=>{if(zb.k==="div"){const xx=zAus==="mitte"?zW/2:L+zW*.01;e.add(new zFb.Line([xx,y,xx,y+zb.h],{stroke:AK,strokeWidth:Math.max(1.5,zW*.0025),...zNo}))}
else if(zb.lines.length){const st=zb.st,fs=zb.fs,lh=fs*st.lh,zPad=st.bub?fs*.6:0,zBw=st.bub?Math.max(...zb.lines.map(zq=>zq.w))+2*zPad:0,zBx=zb.k==="br"?zW-L-zBw:L;st.bub&&e.add(new zFb.Rect({left:zBx,top:y,width:zBw,height:zb.h,rx:fs*.75,ry:fs*.75,fill:zb.k==="br"?AK:"rgba(255,255,255,0.9)",shadow:new zFb.Shadow({color:"rgba(0,0,0,0.12)",blur:zW*.02,offsetX:0,offsetY:zW*.004}),...zNo}));zb.lines.forEach((zl,zi)=>{const yc=y+zPad+lh*zi+lh/2;const x0=st.bub?zBx+zPad:zb.k==="li"?L+LI:zb.k==="hand"&&zb.kom?L+zW*.32:zAus==="mitte"?(zW-zl.w)/2:L;st.bar&&e.add(new zFb.Rect({left:x0-fs*.45,top:yc-fs*.7,width:zl.w+fs*.9,height:fs*1.4,fill:AK,...zNo}));if(zb.k==="h1"&&zi===zb.lines.length-1){const zLt=zl.segs.map(zq=>zq.t).join("").trim(),zLw=zLt.split(/\s+/).pop();const zWw=zMs(zLw,`${st.w} ${fs}px "${st.fam}"`,fs,st.cs);zLW={x:x0+zl.w-zWw,w:zWw,yc,fs}}if(zb.k==="hand"&&zi===0&&st.tilt&&!zb.kom)zHY={x:x0,yc,fs};if(zb.k==="amp"&&zi===zb.lines.length-1)zAmpL={x0,w:zl.w,yc,fs,t:!!st.tilt,bar:!!st.bar};if(zb.k==="strike"){const zy0=yc+fs*.02,zj=((zi*7+3)%5-2)*fs*.04;zDurch.push(`M ${x0-fs*.15} ${zy0+zj} C ${x0+zl.w*.3} ${zy0-fs*.08}, ${x0+zl.w*.65} ${zy0+fs*.1}, ${x0+zl.w+fs*.15} ${zy0-zj}`)}
if(zb.k==="li"&&zi===0){const ax=L,aw=zW*.058,sw=Math.max(1.5,zW*.0032);e.add(new zFb.Line([ax,yc,ax+aw,yc],{stroke:AK,strokeWidth:sw,strokeLineCap:"round",...zNo}));e.add(new zFb.Polyline([{x:ax+aw-fs*.32,y:yc-fs*.22},{x:ax+aw,y:yc},{x:ax+aw-fs*.32,y:yc+fs*.22}],{fill:"",stroke:AK,strokeWidth:sw,strokeLineCap:"round",strokeLineJoin:"round",...zNo}))}
let xx=x0;const zg=[];zl.segs.forEach(sg=>{const zq=zg[zg.length-1];zq&&zq.b===sg.b&&zq.u===sg.u&&zq.c===sg.c&&zq.i===sg.i?(zq.t+=sg.t,zq.w+=sg.w):zg.push({...sg})});
zg.forEach(sg=>{const zMk=zGim==="marker"&&zb.k==="h1"&&sg.c,zDk=st.bub||zMk||st.bar;zMk&&e.add(new zFb.Rect({left:xx-fs*.12,top:yc-fs*.44,width:sg.w-zMs((/\s+$/.exec(sg.t)||[""])[0],`${st.w} ${fs}px "${st.fam}"`,fs,st.cs)+fs*.24,height:fs*.92,rx:fs*.08,ry:fs*.08,angle:-.6,fill:AK,opacity:.92,...zNo}));let zT2=sg.t,zX2=xx,zY2=yc;if(zb.k==="amp"&&st.tilt&&/^&/.test(zT2)){const zfA=fs*1.12,wA=zMs("&",`italic ${KW} ${zfA}px "${KUR}"`,zfA,0);e.add(new zFb.Text("&",{left:xx,top:yc,originX:"left",originY:"center",fontFamily:KUR,fontStyle:"italic",fontWeight:KW,fontSize:zfA,fill:AK,angle:-3,shadow:zSch,...zNo}));zX2=xx+wA;zY2=yc-wA*Math.tan(3*Math.PI/180);zT2=zT2.slice(1)}const zTO=new zFb.Text(zT2,{left:zX2,top:zY2,originX:"left",originY:"center",fontFamily:sg.i&&K.magKursivLaufSchrift?K.magKursivLaufSchrift:st.fam,fontWeight:sg.b&&st.fam===SANS?"600":sg.i&&K.magKursivLaufGewicht?String(K.magKursivLaufGewicht):st.w,fontStyle:st.it||sg.i?"italic":"normal",fontSize:fs,charSpacing:st.cs||0,fill:zb.k==="zahl"?"":zDk?"#1E2B30":(sg.c||zb.k==="caps"||zb.k==="hand"||zb.k==="amp"||zb.k==="wm3")?AK:TXT,stroke:zb.k==="zahl"?TXT:void 0,strokeWidth:zb.k==="zahl"?Math.max(1.5,zW*.0024):0,opacity:zb.k==="strike"?.88:1,angle:st.tilt||0,shadow:zDk||zb.k==="zahl"?void 0:zSch,...zNo});e.add(zTO);
if(sg.u){const tw=sg.w-zMs((/\s+$/.exec(sg.t)||[""])[0],`600 ${fs}px "${st.fam}"`,fs,0);zStrich(xx,xx+tw,yc+fs*.62,fs)}xx+=zb.k==="amp"?sg.w:Math.max(sg.w,(zTO.width||0)+(zX2-xx)+(/\s$/.test(sg.t)&&!/\s$/.test(zTO.text||"")?zMs(" ",`400 ${fs}px "${st.fam}"`,fs,st.cs):0))})})}
y+=zb.h+(zx<zB.length-1?zGap(zb,zB[zx+1]):0)});
if(zAmpL&&!zAmpL.t){const{x0,w,yc,fs}=zAmpL,sw=Math.max(1.5,zW*.0024),ax=x0+w+(zAmpL.bar?fs*.9:fs*.55),aw=Math.max(fs*1.1,zW*.045);if(ax+aw<zW*.93){e.add(new zFb.Line([ax,yc,ax+aw,yc],{stroke:AK,strokeWidth:sw,strokeLineCap:"round",...zNo}));e.add(new zFb.Polyline([{x:ax+aw-zW*.012,y:yc-zW*.009},{x:ax+aw,y:yc},{x:ax+aw-zW*.012,y:yc+zW*.009}],{fill:"",stroke:AK,strokeWidth:sw,strokeLineCap:"round",strokeLineJoin:"round",...zNo}))}}else if(zAmpL){const{x0,w,yc,fs}=zAmpL,tn=Math.tan(3*Math.PI/180),sw=Math.max(2,zW*.0036),yA=x=>yc+fs*.6-(x-x0)*tn;e.add(new zFb.Path(`M ${x0-fs*.05} ${yA(x0)} C ${x0+w*.35} ${yA(x0+w*.35)+fs*.12}, ${x0+w*.7} ${yA(x0+w*.7)-fs*.07}, ${x0+w+fs*.08} ${yA(x0+w)-fs*.02}`,{fill:"",stroke:AK,strokeWidth:sw,strokeLineCap:"round",...zNo}));e.add(new zFb.Path(`M ${x0+w*.12} ${yA(x0+w*.12)+fs*.16} C ${x0+w*.45} ${yA(x0+w*.45)+fs*.2}, ${x0+w*.75} ${yA(x0+w*.75)+fs*.08}, ${x0+w*.92} ${yA(x0+w*.92)+fs*.12}`,{fill:"",stroke:AK,strokeWidth:sw*.6,strokeLineCap:"round",opacity:.8,...zNo}));const ax=x0+w+fs*.32,ay=yc-w*tn;if(ax+fs*1.05<zW*.95){e.add(new zFb.Path(`M ${ax} ${ay+fs*.08} Q ${ax+fs*.45} ${ay-fs*.28} ${ax+fs*.95} ${ay}`,{fill:"",stroke:AK,strokeWidth:sw,strokeLineCap:"round",...zNo}));e.add(new zFb.Polyline([{x:ax+fs*.66,y:ay-fs*.2},{x:ax+fs*.95,y:ay},{x:ax+fs*.66,y:ay+fs*.2}],{fill:"",stroke:AK,strokeWidth:sw,strokeLineCap:"round",strokeLineJoin:"round",...zNo}))}}zDurch.forEach(zd=>e.add(new zFb.Path(zd,{fill:"",stroke:AK,strokeWidth:Math.max(2,zW*.0034),strokeLineCap:"round",...zNo})));if(zGim==="kringel"&&zLW){const zs=zLW.fs,cx=zLW.x+zLW.w/2,rx=zLW.w/2+zs*.28,ry=zs*.58,sw=Math.max(1.5,zW*.0028);e.add(new zFb.Path(`M ${cx-rx*.9} ${zLW.yc+ry*.2} C ${cx-rx*1.05} ${zLW.yc-ry*1.1}, ${cx+rx*.7} ${zLW.yc-ry*1.25}, ${cx+rx} ${zLW.yc-ry*.2} C ${cx+rx*1.2} ${zLW.yc+ry*.9}, ${cx-rx*.2} ${zLW.yc+ry*1.15}, ${cx-rx*.85} ${zLW.yc+ry*.75} C ${cx-rx*1.1} ${zLW.yc+ry*.5}, ${cx-rx*1.0} ${zLW.yc-ry*.6}, ${cx-rx*.55} ${zLW.yc-ry*.85}`,{fill:"",stroke:AK,strokeWidth:sw,strokeLineCap:"round",...zNo}));
if(zHY&&zHY.yc-zLW.yc<zLW.fs*1.9){const ax=cx-rx*.3,ay=zLW.yc+ry*1.2,bx=Math.max(zHY.x+zHY.fs*2.2,ax+zW*.02),by=zHY.yc-zHY.fs*.75;e.add(new zFb.Path(`M ${ax} ${ay} Q ${ax-zW*.01} ${(ay+by)/2+zW*.02} ${bx} ${by}`,{fill:"",stroke:AK,strokeWidth:sw*.85,strokeLineCap:"round",...zNo}));e.add(new zFb.Polyline([{x:bx-zW*.025,y:by-zW*.008},{x:bx,y:by},{x:bx-zW*.012,y:by+zW*.022}],{fill:"",stroke:AK,strokeWidth:sw*.85,strokeLineCap:"round",strokeLineJoin:"round",...zNo}))}}
const zFbx=t._zBox,zLinks=!!(zFbx&&typeof zFbx.x0==="number"&&(zFbx.x0+zFbx.x1)/2>.55);
if(zGim==="sticker"){const zr2=zW*.112,zcx=zLinks?zW*.24:zW*.76,zcy=Math.max(zH*.13+zr2,Math.min(zH*.28,zY0-zH*.04-zr2));e.add(new zFb.Circle({left:zcx,top:zcy,radius:zr2,originX:"center",originY:"center",fill:AK,shadow:new zFb.Shadow({color:"rgba(0,0,0,0.2)",blur:zW*.025,offsetX:0,offsetY:zW*.006}),...zNo}));e.add(new zFb.Circle({left:zcx,top:zcy,radius:zr2*.86,originX:"center",originY:"center",fill:"",stroke:"#1E2B30",strokeWidth:Math.max(1,zW*.0016),opacity:.45,...zNo}));e.add(new zFb.Text(zWahl(K.magSticker,"REAL TALK").split(" ").join("\n"),{left:zcx,top:zcy,originX:"center",originY:"center",textAlign:"center",fontFamily:WIDE,fontWeight:WW,fontSize:zW*.026,lineHeight:1.05,charSpacing:120,fill:"#1E2B30",angle:-12,...zNo}))}
if(zGim==="zettel"&&zGimZettel){const zbw=zW*.38,zfs=zW*.05,zcx=zLinks?zW*.32:zW*.68,zcy0=zH*.3,ztb=new zFb.Textbox(zGimZettel,{width:zbw-zW*.07,fontFamily:HAND,fontWeight:HW,fontSize:zfs,lineHeight:.98,fill:"#1E2B30",textAlign:"left",originX:"center",originY:"center",left:zcx,top:zcy0,angle:2.5,...zNo});const zbh=(ztb.height||zfs*3)+zW*.07,zcy=Math.max(zH*.13+zbh/2,Math.min(zH*.3,zY0-zH*.045-zbh/2));ztb.set("top",zcy);e.add(new zFb.Rect({left:zcx,top:zcy,width:zbw,height:zbh,originX:"center",originY:"center",angle:2.5,fill:"#F7F3EA",shadow:new zFb.Shadow({color:"rgba(0,0,0,0.22)",blur:zW*.035,offsetX:0,offsetY:zW*.01}),...zNo}));e.add(ztb);e.add(new zFb.Rect({left:zcx+Math.sin(2.5*Math.PI/180)*zbh/2,top:zcy-Math.cos(2.5*Math.PI/180)*zbh/2,width:zW*.1,height:zW*.028,originX:"center",originY:"center",angle:-3,fill:AK,opacity:.75,...zNo}))}
K.magRahmen&&e.add(new zFb.Rect({left:zW*.045,top:zW*.045,width:zW*.91,height:zH-zW*.09,fill:"",stroke:TXT,strokeWidth:Math.max(1,zW*.0013),opacity:.38,...zNo}));K.magMonogramm&&e.add(new zFb.Text(String(K.magMonogramm),{left:zW*.905,top:zH*.105,originX:"right",originY:"center",fontFamily:SER,fontWeight:SW,fontSize:zW*.075,charSpacing:-40,fill:TXT,shadow:zSch,...zNo}));if(K.magNummer!==0){const zNr=zCover?(typeof t._tag=="number"?"N° "+String(t._tag).padStart(3,"0"):""):String(((i&&i.slideIndex)||0)+1).padStart(2,"0")+" / "+String((i&&i.totalSlides)||"").padStart(2,"0");zNr&&e.add(new zFb.Text(zNr,{left:L,top:zH*.105,originX:"left",originY:"center",fontFamily:SANS,fontWeight:"500",fontSize:zW*.022,charSpacing:260,fill:TXT,opacity:.82,shadow:zSch,...zNo}))}if(K.magSignatur){const zSl=String(K.magSignatur).split("|").filter(Boolean),zSa=zSl[((Number(t._tag)||0)%zSl.length+zSl.length)%zSl.length];zSa==="schrift"?e.add(new zFb.Text(K.magSigText||"carinaannaprav",{left:zW/2,top:zH*.928,originX:"center",originY:"center",fontFamily:K.magSigSchrift||"Mrs Saint Delafield",fontWeight:"400",fontSize:zW*.062,fill:TXT,opacity:.92,shadow:zSch,...zNo})):e.add(new zFb.Text(K.magSigCaps||"BY CARINA ANNA PRAV",{left:zW/2,top:zH*.935,originX:"center",originY:"center",fontFamily:SANS,fontWeight:"500",fontSize:zW*.017,charSpacing:380,fill:TXT,opacity:.85,shadow:zSch,...zNo}))}
t.overlayImage&&await Ae(t.overlayImage).catch(()=>{});e.renderAll();return}'''
SCRAP = open(__file__.rsplit('/', 1)[0] + '/scrap-zeichner.js', encoding='utf-8').read().split('*/', 1)[1].strip()
KLARZ = open(__file__.rsplit('/', 1)[0] + '/klar-zeichner.js', encoding='utf-8').read().split('*/', 1)[1].strip()
PREMZ = open(__file__.rsplit('/', 1)[0] + '/premium-zeichner.js', encoding='utf-8').read().split('*/', 1)[1].strip()
ZEICHNER = ZEICHNER.replace('if(zCover&&!zMark&&K.magCoverInline===1)', KLARZ + PREMZ + SCRAP + 'if(zCover&&!zMark&&K.magCoverInline===1)', 1).replace('zTyp==="flaeche"&&(zSch=void 0);', '(zTyp==="flaeche"||zTyp0==="scrap")&&(zSch=void 0);', 1)
ANKER = 'if($e&&(t.karte==="ablauf"||t.reminderArt==="ablauf")){const Ab=T1('
ersetze(ANKER, ZEICHNER.replace('\n', '') + ANKER)
ersetze('title:"Geladene Datei",children:"karten451"', f'title:"Geladene Datei",children:"karten{VERSION}"')
open(Z, 'w', encoding='utf-8').write(s)
print('ok')
